### ISSUE TITLE
Automatically convert bool tag value into string tag

### ISSUE THREAD

**Issue by lukekim** [spiceai/data-components-contrib#39]
E.g.

```yaml
tags:
  selectors:
    - private
  values:
    - private
```

```json
{
     "private": true
}
```

Creates the observation

```json
{
    "tags": "private"
}
```
